# sets user-defined palette (theme)
palette = "catppuccin_mocha"

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_status\
$kubernetes\
$terraform\
$python\
$golang\
$nodejs\
$rust\
$lua\
$cmd_duration\
$line_break\
$character"""

[directory]
style = "bold green"

[directory.substitutions]
'Documents' = '󰈙'
'Downloads' = ' '
'Music' = ' '
'Pictures' = ' '

[character]
error_symbol = "[󰩈](bold red)"
success_symbol = "[](bold green)"
vicmd_symbol = "[](bold teal)"

[cmd_duration]
style = "bold yellow"
min_time = 2_000

[git_branch]
symbol = ''
format = '[on](white) [$symbol$branch]($style) '

[git_commit]
only_detached = true
tag_disabled = false
tag_symbol = ''
format = '[$tag]($style)'

[git_status]
format = '([$ahead_behind$modified$staged$untracked]($style) )'
style = "bold peach"
modified = "~${count}"
staged = "+${count}"
untracked = "?${count}"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇡${ahead_count}⇣${behind_count}"

[kubernetes]
symbol = '☸ '
disabled = false
detect_files = ['Dockerfile', '.cluster']
format = '[$context(\[$namespace\])]($style) '

[kubernetes.context_aliases]

[terraform]
symbol = '󱁢 '
style = 'bold lavender'
format = '[$symbol$workspace]($style) '

[python]
style = 'teal'
symbol = ' '
format = '[${symbol}(${version} )(\($virtualenv\) )]($style)'

[golang]
style = 'blue'
symbol = ' '

[nodejs]
style = 'blue'
symbol = ' '

[lua]
symbol = ' '

[rust]
style = 'peach'
symbol = ' '

[haskell]
style = 'blue'
symbol = ' '

[username]
format = "[$user]($style) "

[hostname]

[nix_shell]
disabled = true
format = ""

[docker_context]
disabled = true

[gcloud]
disabled = true

[aws]
disabled = true

[azure]
disabled = true

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
