# Git abbreviations

abbr g git
abbr ga "git add ."
abbr gaa "git add --all"
abbr gb "git branch -v"
abbr gbD "git branch -D"
abbr gbd "git branch -d"
abbr gc "git commit"
abbr gca "git commit -av"
abbr gcb "git checkout -b"
abbr gcl "git clone"
abbr gcmsg "git commit --message"
abbr gco "git checkout"
abbr gcom "git checkout main"
abbr gd "git diff"
abbr gds "git diff --staged"
abbr gf "git fetch --all"
abbr gi "git init"
abbr gl "git pull"
abbr glog "git log --oneline --decorate --graph"
abbr glr "git pull --rebase"
abbr gma "git merge --abort"
abbr gmc "git merge --continue"
abbr gp "git push"
abbr gpf "git push --force"
abbr gpom "git pull origin main"
abbr gpr "gh pr create"
abbr gbsu "git branch --set-upstream-to=origin/(git rev-parse --abbrev-ref HEAD) (git rev-parse --abbrev-ref HEAD)"
abbr gpsup "git push --set-upstream origin (git rev-parse --abbrev-ref HEAD)"
abbr gpum "git pull upstream master"
abbr gr "git remote"
abbr gra "git rebase --abort"
abbr grao "git remote add origin"
abbr grau "git remote add upstream"
abbr grc "git rebase --continue"
abbr grhh "git reset --hard"
abbr grhs "git reset --soft"
abbr grro "git remote remove origin"
abbr grs "git restore"
abbr grst "git restore --staged"
abbr grv "git remote -v"
abbr gs "git status"
abbr gst "git status"
abbr gsta "git stash push"
abbr gstaa "git stash apply"
abbr gstall "git stash --all"
abbr gstc "git stash clear"
abbr gstd "git stash drop"
abbr gstl "git stash list"
abbr gstp "git stash pop"
abbr gsts "git stash show --text"

abbr lg lazygit
