bind -N "workmux menu" w run-shell "~/.config/tmux/scripts/workmux-menu.sh"
bind -N "workmux dashboard" g display-popup -E -w 90% -h 90% "workmux dashboard"
bind -N "toggle workmux sidebar" W run-shell "workmux sidebar"
