# Aliases for bash — equivalent to fish abbreviations

# --- Editor & Vim-style ---
alias vim='nvim'
alias v='nvim .'
alias python='python3'

# --- Git ---
alias g='git'
alias ga='git add .'
alias gaa='git add --all'
alias gb='git branch -v'
alias gbd='git branch -d'
alias gbD='git branch -D'
alias gbsu='git branch --set-upstream-to=origin/$(git rev-parse --abbrev-ref HEAD) $(git rev-parse --abbrev-ref HEAD)'
alias gc='git commit'
alias gca='git commit -av'
alias gcb='git checkout -b'
alias gcl='git clone'
alias gcmsg='git commit --message'
alias gco='git checkout'
alias gcom='git checkout main'
alias gd='git diff'
alias gds='git diff --staged'
alias gf='git fetch --all'
alias gi='git init'
alias gl='git pull'
alias glog='git log --oneline --decorate --graph'
alias glr='git pull --rebase'
alias gma='git merge --abort'
alias gmc='git merge --continue'
alias gp='git push'
alias gpf='git push --force'
alias gpom='git pull origin main'
alias gpr='gh pr create'
alias gpsup='git push --set-upstream origin $(git rev-parse --abbrev-ref HEAD)'
alias gpum='git pull upstream master'
alias gr='git remote'
alias gra='git rebase --abort'
alias grao='git remote add origin'
alias grau='git remote add upstream'
alias grc='git rebase --continue'
alias grhh='git reset --hard'
alias grhs='git reset --soft'
alias grro='git remote remove origin'
alias grs='git restore'
alias grst='git restore --staged'
alias grv='git remote -v'
alias gs='git status'
alias gst='git status'
alias gsta='git stash push'
alias gstaa='git stash apply'
alias gstall='git stash --all'
alias gstc='git stash clear'
alias gstd='git stash drop'
alias gstl='git stash list'
alias gstp='git stash pop'
alias gsts='git stash show --text'
alias lg='lazygit'

# --- Jujutsu (jj) ---
alias jji='jj git init'
alias jjic='jj git init --colocate'
alias jjgc='jj git clone'
alias jjd='jj diff'
alias jjds='jj diff --staged'
alias jjst='jj status'
alias jjl='jj log'
alias jjla='jj log --all'
alias jjlg='jj log --graph'
alias jjn='jj new'
alias jjc='jj commit'
alias jjcm='jj commit -m'
alias jjdesc='jj describe'
alias jjdm='jj describe -m'
alias jjsq='jj squash'
alias jjsp='jj split'
alias jjr='jj restore'
alias jjrs='jj restore --source'
alias jjco='jj checkout'
alias jjcob='jj new -r'
alias jjcom='jj new -r main'
alias jjbm='jj bookmark'
alias jjbmc='jj bookmark create'
alias jjbmd='jj bookmark delete'
alias jjbmm='jj bookmark move'
alias jjf='jj git fetch'
alias jjgpl='jj git pull'
alias jjgps='jj git push'
alias jjgpsa='jj git push --all'
alias jjgpsnew='jj git push --allow-new'
alias jjrb='jj rebase -d'
alias jju='jj undo'
alias jjua='jj abandon'
alias jjob='jj obslog'
alias jjh='jj help'

# --- Kubernetes / kubectl ---
alias k='kubectl'
alias ka='kubectl apply -f'
alias kc='kubectx'
alias kcns='kubectl config set-context --current --namespace'
alias kd='kubectl describe'
alias kdel='kubectl delete'
alias ke='kubectl exec -it'
alias kg='kubectl get'
alias kgd='kubectl get deployments'
alias kgpo='kubectl get pod'
alias kl='kubectl logs'
alias kns='kubens'
alias k9s='k9s --logoless --splashless --all-namespaces'

# --- Docker ---
alias dc='docker compose'
alias dcd='docker compose down'
alias dcdv='docker compose down -v'
alias dcr='docker compose restart'
alias dcu='docker compose up -d'
alias dps="docker ps --format 'table {{.Names}}\t{{.Status}}'"
alias ld='lazydocker'
alias p='podman'

# --- Terraform ---
alias tf='terraform'
alias tfa='terraform apply'
alias tfaa='terraform apply --auto-approve'
alias tfd='terraform destroy'
alias tfda='terraform destroy --auto-approve'
alias tff='terraform fmt'
alias tffr='terraform fmt --recursive'
alias tfi='terraform init'
alias tfiu='terraform init --upgrade'
alias tfm='terraform format'
alias tfo='terraform output'
alias tfp='terraform plan'
alias tfpr='terraform plan --refresh-only'
alias tfs='terraform state'
alias tfsl='terraform state list'
alias tfss='terraform state show'
alias tfv='terraform validate'

# --- Terragrunt ---
alias tg='terragrunt'
alias tgaa='terragrunt run-all apply'
alias tgaaa='terragrunt run-all apply --auto-approve'
alias tgad='terragrunt run-all destroy'
alias tgada='terragrunt run-all destroy --auto-approve'
alias tgaf='terragrunt run-all fmt'
alias tgai='terragrunt run-all init'
alias tgaiu='terragrunt run-all init --upgrade'
alias tgap='terragrunt run-all plan'
alias tgav='terragrunt run-all validate'

# --- NPM / Node.js ---
alias nb='npm run build'
alias nd='npm run dev'
alias ne='nvim .env'
alias ni='npm install'
alias nt='npm run test'

# --- Python / Pre-commit ---
alias pc='pre-commit'
alias pcc='pre-commit clean'
alias pci='pre-commit install'
alias pcr='pre-commit run'
alias pcra='pre-commit run --all-files'
alias pcrf='pre-commit run --files'
alias pcrv='pre-commit run --verbose'
alias pcu='pre-commit uninstall'
alias pcup='pre-commit autoupdate'
alias pfr='pip3 freeze > ./requirements.txt'
alias venv='python3 -m venv .venv && source .venv/bin/activate'

# --- Tmux ---
alias st='tmux source ~/.config/tmux/tmux.conf'
alias t='tmux'
alias ta='tmux a'
alias tat='tmux attach -t'
alias td='t dotfiles'
alias tk='tmux kill-server'
alias tks='tmux kill-server'
alias tn='tmux new -s $(basename $(pwd))'
alias tt='touch .t && chmod +x .t && echo -e "#!/usr/bin/env bash\n" > .t && nvim .t'

# --- File Listing (eza) ---
alias l='eza --group-directories-first -Al'
alias ll='eza --all --git --icons --color=always --group-directories-first -Al'
alias lt='eza --group-directories-last --tree'
alias lta='eza --group-directories-last --tree --all --ignore-glob=".git|node_modules|.venv|.terraform|"'
alias ltd='eza --group-directories-last --tree --only-dirs'

# --- Directory Navigation ---
alias ..='cd ..'
alias ...='cd ../../../'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'

# --- Zoxide ---
alias za='zoxide add'
alias ze='zoxide edit'

# --- Direnv ---
alias da='direnv allow'
alias dr='direnv reload'

# --- Homebrew ---
alias bi='brew install'
alias bic='brew install --cask'
alias bin='brew info'
alias binc='brew info --cask'
alias bl='brew leaves'
alias blr='brew leaves --installed-on-request'
alias blp='brew leaves --installed-as-dependency'
alias bs='brew search'

# --- System & Utility ---
alias c='clear'
alias cl='clear'
alias claer='clear'
alias clera='clear'
alias cx='chmod +x'
alias e='exit'
alias mt='man tmux'
alias mf='man fzf'
alias mz='man zoxide'
alias nf='neofetch'
alias o='open .'
alias rgi='rg -i'
alias rmr='rm -rf'
alias sb='source ~/.bashrc'

# --- Cloud & GCP ---
alias gcsp='gcloud config set project'
