name: Create Tag and Release
on:
  pull_request:
    types: [closed]
jobs:
  create-tag-and-release:
    name: Create Tag and Release
    uses: lowranceworks/common-workflows/.github/workflows/create-tag-and-release.yaml@main
    permissions:
      contents: write
      pull-requests: read
      issues: read
